apiVersion: v1
kind: Secret
metadata:
  name: mongo-secrets
type: Opaque
data:
  # MONGO_URI: <base64-encoded-mongo-uri> # Encode the Mongo URI in base64
  MONGO_URI: bW9uZ29kYjovL2xvY2FsaG9zdDoyNzAxNy9zZWN1cmUtZnVsbHN0YWNrLWFwcC1pbi1rOHM=
